# Generated by Django 2.2.2 on 2020-01-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airqualityapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='co2',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
            preserve_default=False,
        ),
    ]
